### ISSUE TITLE
Time to restructure voelzlab/peptoids?

### ISSUE THREAD

**Issue by vvoelz** [vvoelz/voelzlab#20]
# The current directory structure of voelzlab/peptoids is driving me nuts.

I propose something like:

    voelzlab/
        custom_topologies/
            scripts/
            residues/ <-- a library of AMBER residue topologies with head and/or tali
            peptoids <-- specific peptoids built from residues
            [your name here] < -- other molecules built stand-alone, or from residues

**Comment by gfzhou** [comment]
The new directory structure looks good to me.

**Comment by sudipto-mukherjee** [comment]
Restructuring is complete. Spiroligomer folder was also moved to custom trajectories. George is going to compile the folders inside into residues, spiroligomers and mol2 files for docking.
